region              = "eu-west-3"
ami_id              = "ami-0e1c4170d9c01184b"
instance_count      = 1
instance_type       = "t3.micro"
security_group_name = "aws-sg-for-load-balancer"
load_b              = "Terraform-lb"
# domain_name         = "TTYAbdoTTy.com"
environment         = "production"
public_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL0UC2aCDDT59efQwonJipHTgIapUxouQrGNQLEFCfMK abdo@archlinux"